#!/bin/bash

# Dotfiles home
export DOTFILES_HOME=${HOME}/.dotfiles

# Android
export ANDROID_SDK_HOME=${HOME}/Android
export ANDROID_STUDIO_HOME=${HOME}/android-studio
export ANDROID_PLATFORM_TOOLS=${ANDROID_SDK_HOME}/Sdk/platform-tools
# Append the NDK version folder at the end of this path
export ANDROID_NDK_HOME=${ANDROID_SDK_HOME}/Sdk/ndk/25.2.9519653

# Flutter
export FLUTTER_SDK_HOME=${HOME}/flutter/
export FLUTTER_TOOLS="${FLUTTER_SDK_HOME}/bin"

# Images
export WALLPAPERS_HOME=${DOTFILES_HOME}/wallpapers

# Screen layouts
export SCREENLAYOUT_HOME=${DOTFILES_HOME}/screenlayout

# Shorcuts
export SHORTCUTS_HOME=${DOTFILES_HOME}/bin 

# Scripts
export SCRIPTS_HOME=${DOTFILES_HOME}/scripts

export PATH=${PATH}:${SCRIPTS_HOME}:${SHORTCUTS_HOME}:${ANDROID_PLATFORM_TOOLS}:${FLUTTER_TOOLS}

