name: Nix Flake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Evaluate & Check Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check Formatting
        run: nix fmt -- --check .

      - name: Evaluate Flake Checks
        run: nix flake check --no-build --extra-experimental-features "nix-command flakes"
